import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdtemp, mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import test from "node:test";

// These compile the guide's templates in disposable fixtures, not a Core subject.
const repo = fileURLToPath(new URL("../", import.meta.url));
const require = createRequire(import.meta.url);
const tsc = join(dirname(require.resolve("typescript/package.json")), "bin/tsc");
const guide = await readFile(join(repo,
  "docs/architecture/self-composition-implementation-guide.md"), "utf8");
const wiring = guide.match(/```ts\n(\/\/ generated by the self-composition emitter[\s\S]*?)\n```/u)?.[1];
assert.ok(wiring, "the guide must retain its executable generated-root example");
function config(name) {
  const marker = `<!-- build-config: ${name} -->`;
  const body = guide.slice(guide.indexOf(marker) + marker.length)
    .match(/^\s*```json\n([\s\S]*?)\n```/u)?.[1];
  assert.ok(guide.includes(marker) && body, `missing guide config ${name}`);
  return JSON.parse(body);
}
async function put(root, path, contents) {
  const target = join(root, path);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, contents);
}
function compile(root, project) {
  const run = spawnSync(process.execPath, [tsc, "-p", project, "--pretty", "false"], {
    cwd: root, encoding: "utf8", timeout: 20_000,
  });
  assert.ifError(run.error);
  return { status: run.status, output: run.stdout + run.stderr };
}
async function fixture(t) {
  const root = await mkdtemp(join(tmpdir(), "get-modular-guide-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  await put(root, "package.json", '{"type":"module","private":true}\n');
  // Keep the actual pinned compiler options, with only its extends path made absolute.
  const base = JSON.parse(await readFile(join(repo, "tsconfig.base.json"), "utf8"));
  base.extends = require.resolve(base.extends);
  await put(root, "tsconfig.base.json", JSON.stringify(base));
  const core = join(root, "packages/core");
  await put(core, "src/features/authoring/internal.ts",
    "export interface Service { readonly value: number; }\n");
  for (const [path, name] of [
    ["canonicalization/owned-jcs", "createOwnedJcs"],
    ["composition-semantics", "createCompositionSemantics"],
    ["input-admission", "createInputAdmission"],
    ["plan-output", "createPlanOutput"],
  ]) {
    const prefix = path.includes("/") ? "../../" : "../";
    await put(core, `src/features/${path}/factory.ts`,
      `import type { Service } from "${prefix}authoring/internal.js";\n`
      + `export function ${name}(deps: Readonly<Record<string, Service>>): Service {\n`
      + "  return { value: Object.keys(deps).length };\n}\n");
  }
  await put(core, "src/features/compiler-facade/ports.ts",
    "export interface CompilerFacade { compileComposition(): number; }\n");
  await put(core, "src/features/compiler-facade/factory.ts",
    'import type { CompilerFacade } from "./ports.js";\n'
    + 'import type { Service } from "../authoring/internal.js";\n'
    + "export function createCompilerFacade(deps: { admission: Service; semantics: Service; output: Service }): CompilerFacade {\n"
    + "  return { compileComposition: () => deps.semantics.value };\n}\n");
  await put(core, "tsconfig.json", JSON.stringify(config("tsconfig.json")));
  await put(core, "tsconfig.seed.json", JSON.stringify(config("tsconfig.seed.json")));
  return core;
}

test("generated root supports isolated declaration emit and a closed public type surface", async t => {
  const core = await fixture(t);
  await put(core, "src/index.ts",
    'import { root } from "./composition/generated/stage1.js";\n'
    + "export const compileComposition: () => number = root.compileComposition;\n");
  const path = "src/composition/generated/stage1.ts";
  await put(core, path, wiring);
  let result = compile(core, "tsconfig.json");
  assert.equal(result.status, 0, result.output);
  const declaration = await readFile(join(core, "dist/index.d.ts"), "utf8");
  assert.match(declaration, /compileComposition/u);
  assert.doesNotMatch(declaration, /factory|CompilerFacade|composition\//u);
  // Reproduce the original defect, so a passing stub cannot mask the regression.
  await put(core, path, wiring.replace("root: CompilerFacade", "root"));
  result = compile(core, "tsconfig.json");
  assert.notEqual(result.status, 0);
  assert.match(result.output, /TS9010/u);
});

test("cold variant seed builds before a generated entry exists", async t => {
  const core = await fixture(t);
  await put(core, "self-composition/stage0-entry.variant.ts", "export {};\n");
  for (const name of ["own-profile.variant", "allowlist.variant", "emit"]) {
    await put(core, `self-composition/${name}.ts`, "export {};\n");
  }
  await put(core, "self-composition/stage1-entry.variant.ts",
    'export { root } from "../src/composition/generated/stage1.variant.js";\n');
  const qualification = config("tsconfig.seed.json");
  qualification.compilerOptions.outDir = "dist-qualification";
  qualification.files.push("self-composition/stage1-entry.variant.ts");
  await put(core, "tsconfig.qualification.json", JSON.stringify(qualification));
  let result = compile(core, "tsconfig.qualification.json");
  assert.notEqual(result.status, 0);
  assert.match(result.output, /TS2307/u);
  result = compile(core, "tsconfig.seed.json");
  assert.equal(result.status, 0, result.output);
  // Stand in only for the emitter's file write; no semantic generation is claimed.
  await put(core, "src/composition/generated/stage1.variant.ts", wiring);
  result = compile(core, "tsconfig.qualification.json");
  assert.equal(result.status, 0, result.output);
});

test("cold production builds stage0 before emitting the generated root", async t => {
  const core = await fixture(t);
  await put(core, "src/index.ts",
    'import { root } from "./composition/generated/stage1.js";\n'
    + "export const compileComposition: () => number = root.compileComposition;\n");
  await put(core, "src/composition/stage0.ts",
    wiring.replaceAll('"../../features/', '"../features/'));
  await put(core, "self-composition/stage0-entry.ts",
    'export { root } from "../src/composition/stage0.js";\n');
  for (const name of ["own-profile", "allowlist", "emit"]) {
    await put(core, `self-composition/${name}.ts`, "export {};\n");
  }
  // A cold variant entry must not accidentally join the stage0 tooling program.
  await put(core, "self-composition/stage1-entry.variant.ts",
    'export { root } from "../src/composition/generated/stage1.variant.js";\n');
  await put(core, "tsconfig.stage0.json", JSON.stringify(config("tsconfig.stage0.json")));
  let result = compile(core, "tsconfig.json");
  assert.notEqual(result.status, 0);
  assert.match(result.output, /TS2307/u);
  result = compile(core, "tsconfig.stage0.json");
  assert.equal(result.status, 0, result.output);
  // Only model the documented emitter output; the real emitter is M3 work.
  await put(core, "src/composition/generated/stage1.ts", wiring);
  await rm(join(core, "dist"), { recursive: true, force: true });
  result = compile(core, "tsconfig.json");
  assert.equal(result.status, 0, result.output);
});

test("production root selection retains type dependencies and excludes unselected source", async t => {
  const core = await fixture(t);
  await put(core, "src/index.ts",
    'import { root } from "./composition/generated/stage1.js";\n'
    + 'export type { Service } from "./features/authoring/internal.js";\n'
    + "export const compileComposition: () => number = root.compileComposition;\n");
  await put(core, "src/composition/generated/stage1.ts", wiring);
  await put(core, "src/features/unselected/factory.ts",
    'export const sentinel: string = "UNSELECTED_IMPLEMENTATION_SENTINEL";\n');
  // Model output left by a former selection; the documented clean step removes it.
  await put(core, "dist/features/unselected/factory.js", "stale provider\n");
  await rm(join(core, "dist"), { recursive: true });
  const result = compile(core, "tsconfig.json");
  assert.equal(result.status, 0, result.output);
  const paths = await readdir(join(core, "dist"), { recursive: true });
  assert.equal(paths.some(path => path.includes("unselected")), false);
  assert.ok(paths.includes("features/authoring/internal.d.ts"));
  // This proves emit closure only. M3 must separately audit actual packed archives.
});
