import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import test from 'node:test';
import canonicalize from 'canonicalize';
import { version } from 'typescript';
import { compileComposition as direct } from '../../dist-stage0/self-composition/stage0-entry.js';
import { ownDeclarations, ownProfile } from '../../dist-stage0/self-composition/own-profile.js';
import { allowlist } from '../../dist-stage0/self-composition/allowlist.js';
import { verifyConstruction } from '../qualification-support/support/construction-witness.mjs';

const packageRoot = fileURLToPath(new URL('../../', import.meta.url));
const require = createRequire(import.meta.url);
const tsc = join(dirname(require.resolve('typescript/package.json')), 'bin/tsc');
const canon = 'get-modular/canonicalization/owned-jcs';
const semantics = 'get-modular/composition-semantics/default';
const output = 'get-modular/plan-output/default';
const scanner = 'get-modular/raw-scanner/owned-iterative';
const admission = 'get-modular/input-admission/default';
const facade = 'get-modular/compiler-facade/default';
const expectedTuples = [
  [canon, 0, []],
  [semantics, 1, [['canonicalizer', canon]]],
  [output, 2, [['canonicalizer', canon]]],
  [scanner, 3, []],
  [admission, 4, [['scanner', scanner]]],
  [facade, 5, [['admission', admission], ['output', output], ['semantics', semantics]]],
];
const expectedBody = `import { createOwnedJcs } from "../../features/canonicalization/owned-jcs/factory.js";
import { createCompositionSemantics } from "../../features/composition-semantics/factory.js";
import { createPlanOutput } from "../../features/plan-output/factory.js";
import { createOwnedRawScanner } from "../../features/raw-scanner/owned-iterative/factory.js";
import { createInputAdmission } from "../../features/input-admission/factory.js";
import { createCompilerFacade } from "../../features/compiler-facade/factory.js";
import type { CompilerFacadePort } from "../../features/compiler-facade/ports.js";

const canonicalizer = createOwnedJcs({});
const semantics = createCompositionSemantics({ canonicalizer: canonicalizer });
const output = createPlanOutput({ canonicalizer: canonicalizer });
const scanner = createOwnedRawScanner({});
const admission = createInputAdmission({ scanner: scanner });
const compiler = createCompilerFacade({ admission: admission, semantics: semantics, output: output });

export const root: CompilerFacadePort = compiler;
`;

async function write(root, path, text) {
  const target = join(root, path);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, text);
}

function compile(root, config) {
  assert.equal(version, '7.0.2');
  const built = spawnSync(process.execPath, [tsc, '-p', join(root, config)],
    { encoding: 'utf8', timeout: 60_000 });
  assert.ifError(built.error);
  assert.equal(built.signal, null);
  assert.equal(built.status, 0, built.stdout + built.stderr);
}

test('private finite emitter', async t => {
  const temporary = await mkdtemp(join(tmpdir(), 'gm-finite-emitter-'));
  t.after(() => rm(temporary, { recursive: true, force: true }));
  for (const path of ['src', 'self-composition']) {
    await cp(join(packageRoot, path), join(temporary, path), { recursive: true });
  }
  await write(temporary, 'package.json', '{"type":"module"}\n');
  await write(temporary, 'tsconfig.emitter.json', JSON.stringify({
    extends: join(packageRoot, 'tsconfig.json'),
    compilerOptions: { rootDir: '.', outDir: 'built-emitter', skipLibCheck: false },
    files: ['self-composition/emit.ts'],
    include: [],
  }));
  compile(temporary, 'tsconfig.emitter.json');
  const { emitComposition } = await import(pathToFileURL(join(temporary,
    'built-emitter/self-composition/emit.js')).href);
  const result = await direct({ declarations: ownDeclarations, profile: ownProfile });
  assert.equal(result.ok, true);
  const expected = `// generated by the self-composition emitter from plan digest ${result.digest}\n${expectedBody}`;
  const generated = emitComposition(result, allowlist);
  assert.equal(generated, expected);
  assert.equal(emitComposition(result, allowlist), expected);
  assert.equal(emitComposition(result, new Map([...allowlist].reverse())), expected);
  assert.equal(generated.includes('ReturnType'), false);
  for (const selection of result.plan.selections) {
    assert.equal(generated.includes(selection.implementationId), false);
    assert.equal(generated.includes(selection.moduleId), false);
  }

  await t.test('generated private constants compile and satisfy the independent witness', async () => {
    const compositionPath = 'src/composition/generated/stage1.ts';
    await write(temporary, compositionPath, generated);
    await write(temporary, 'tsconfig.generated.json', JSON.stringify({
      extends: join(packageRoot, 'tsconfig.json'),
      compilerOptions: { rootDir: '.', outDir: 'built-generated', skipLibCheck: false },
      files: [compositionPath],
      include: [],
    }));
    compile(temporary, 'tsconfig.generated.json');
    const declaration = await readFile(join(temporary,
      'built-generated/src/composition/generated/stage1.d.ts'), 'utf8');
    assert.match(declaration, /export declare const root: CompilerFacadePort;/u);
    assert.equal(declaration.includes('canonicalizer'), false);
    const witness = await verifyConstruction({
      packageRoot: temporary,
      buildRoot: join(packageRoot, 'dist-stage0'),
      compositionPath,
      allowlistPath: 'self-composition/allowlist.ts',
      plan: result.plan,
    });
    assert.deepEqual(witness, {
      tuples: expectedTuples,
      digest: `sha256:${createHash('sha256').update(canonicalize(expectedTuples)).digest('hex')}`,
    });
  });

  function changedHandle(map, id, changes) {
    map.set(id, { ...map.get(id), ...changes });
  }
  for (const localName of ['constructor', 'async', 'get', 'π', '$owned']) {
    await t.test(`valid local binding ${localName} compiles`, async t => {
      const handles = new Map(allowlist);
      changedHandle(handles, canon, { localName });
      const source = emitComposition(result, handles);
      const expectedSource = expected
        .replace('const canonicalizer =', `const ${localName} =`)
        .replaceAll('canonicalizer: canonicalizer', `canonicalizer: ${localName}`);
      assert.equal(source, expectedSource);
      const compositionPath = 'src/composition/generated/stage1.ts';
      await write(temporary, compositionPath, source);
      compile(temporary, 'tsconfig.generated.json');
    });
  }
  for (const [importPath, modulePath, moduleSource] of [
    ['../../features/canonicalization/owned-jcs/nested/deeper/factory.js',
      'src/features/canonicalization/owned-jcs/nested/deeper/factory.ts',
      'export { createOwnedJcs } from "../../factory.js";\n'],
    ['../../features/canonicalization/owned-jcs/factory-alias.js',
      'src/features/canonicalization/owned-jcs/factory-alias.ts',
      'export { createOwnedJcs } from "./factory.js";\n'],
  ]) {
    await t.test(`safe feature descendant ${importPath} compiles`, async () => {
      const handles = new Map(allowlist);
      changedHandle(handles, canon, { importPath });
      const source = emitComposition(result, handles);
      assert.equal(source, expected.replace(allowlist.get(canon).importPath, importPath));
      await write(temporary, modulePath, moduleSource);
      await write(temporary, 'src/composition/generated/stage1.ts', source);
      compile(temporary, 'tsconfig.generated.json');
    });
  }
  for (const slotId of ['constructor', 'prototype', 'then']) {
    await t.test(`forbidden slot remains independent: ${slotId}`, () => {
      const handles = new Map(allowlist);
      const declaration = structuredClone(allowlist.get(semantics).declaration);
      declaration.slots[0].slotId = slotId;
      changedHandle(handles, semantics, { declaration });
      reject(result, handles, 'emitter.invalid-declaration');
    });
  }
  // Path variants above test the pure renderer and real compiler. The unchanged
  // witness separately requires factory.js beside its owned declaration.
  function reject(candidate, handles, code) {
    let rendered;
    assert.throws(() => { rendered = emitComposition(candidate, handles); }, error => {
      assert.equal(error instanceof Error, true);
      assert.equal(error.code, code);
      assert.equal(error.message, code);
      return true;
    });
    assert.equal(rendered, undefined);
  }
  const negatives = [
    ['failure result', 'emitter.invalid-result', state => { state.result = { ok: false, diagnostics: [] }; }],
    ['unsafe digest', 'emitter.invalid-result', state => { state.result.digest += '\nimport "bad";'; }],
    ['plan field', 'emitter.invalid-plan', state => { state.result.plan.extra = true; }],
    ['missing selected handle', 'allowlist.missing-for-selected', state => { state.handles.delete(canon); }],
    ['missing declaration', 'allowlist.unknown-implementation', state => {
      changedHandle(state.handles, canon, { declaration: undefined });
    }],
    ['wrong declaration identity', 'allowlist.unknown-implementation', state => {
      changedHandle(state.handles, canon, { declaration: allowlist.get(scanner).declaration });
    }],
    ['invalid declaration', 'emitter.invalid-declaration', state => {
      changedHandle(state.handles, canon, { declaration: { ...allowlist.get(canon).declaration, slots: null } });
    }],
    ['nonfunction factory', 'emitter.invalid-factory', state => {
      changedHandle(state.handles, canon, { factory: {} });
    }],
    ['duplicate local', 'allowlist.duplicate-local-name', state => {
      changedHandle(state.handles, canon, { localName: 'scanner' });
    }],
    ['missing root selection', 'emitter.invalid-selection', state => {
      state.result.plan.selections = state.result.plan.selections.filter(row => row.implementationId !== facade);
    }],
    ['duplicate selection', 'emitter.invalid-selection', state => {
      state.result.plan.selections.push(state.result.plan.selections[0]);
    }],
    ['missing order member', 'emitter.invalid-order', state => { state.result.plan.dependencyOrder.pop(); }],
    ['duplicate order member', 'emitter.invalid-order', state => { state.result.plan.dependencyOrder[1] = canon; }],
    ['provider after consumer', 'emitter.invalid-order', state => { state.result.plan.dependencyOrder.reverse(); }],
    ['missing binding', 'emitter.invalid-binding', state => { state.result.plan.bindings.pop(); }],
    ['extra binding', 'emitter.invalid-binding', state => { state.result.plan.bindings.push(state.result.plan.bindings[0]); }],
    ['unknown slot', 'emitter.invalid-binding', state => { state.result.plan.bindings[0].slotId = 'unknown'; }],
    ['empty providers', 'emitter.invalid-binding', state => { state.result.plan.bindings[0].providerImplementationIds = []; }],
    ['multiple providers', 'emitter.invalid-binding', state => { state.result.plan.bindings[0].providerImplementationIds.push(canon); }],
    ['unselected provider', 'emitter.invalid-binding', state => { state.result.plan.bindings[0].providerImplementationIds = ['x/unselected']; }],
    ['incompatible provider', 'emitter.invalid-binding', state => { state.result.plan.bindings[0].compatibility["token"] = "x/incompatible"; }],
  ];
  for (const cardinality of [{ kind: 'optional' }, { kind: 'many', min: 0, max: 1, order: 'profile' }]) {
    negatives.push([cardinality.kind, 'emitter.unsupported-cardinality', state => {
      const declaration = structuredClone(allowlist.get(semantics).declaration);
      declaration.slots[0].cardinality = cardinality;
      changedHandle(state.handles, semantics, { declaration });
    }]);
  }
  for (const localName of ['root', 'CompilerFacadePort', 'createOwnedJcs', 'createInputAdmission']) {
    negatives.push([`local collision ${localName}`, 'emitter.binding-name-collision', state => {
      changedHandle(state.handles, canon, { localName });
    }]);
  }
  for (const factoryExport of ['createOwnedJcs', 'root', 'CompilerFacadePort']) {
    negatives.push([`import collision ${factoryExport}`, 'emitter.binding-name-collision', state => {
      changedHandle(state.handles, scanner, { factoryExport });
    }]);
  }
  for (const field of ['localName', 'factoryExport', 'declarationExport']) {
    for (const value of ['bad-name', 'eval', 'arguments', 'await', 'const', 'class',
      'import', 'enum', 'implements', 'let', 'yield', '1name', '\u0301name', 'a-b']) {
      negatives.push([`${field} ${value}`, 'allowlist.invalid-identifier', state => {
        changedHandle(state.handles, canon, { [field]: value });
      }]);
    }
  }
  for (const importPath of ['/tmp/factory.js', '../../features/../factory.js',
    '../../features/canonicalization/owned-jcs/factory.ts',
    '../../features/canonicalization/./factory.js',
    '../../features/canonicalization/nested/../../factory.js',
    '../../features/canonicalization//factory.js',
    '../../features/canonicalization/factory.js?query',
    '../../features/canonicalization/factory.js#fragment',
    '../../features/canonicalization/"factory.js',
    '../../features/canonicalization/%2e%2e/factory.js',
    '../../../tests/features/canonicalization/witness-variant/factory.js']) {
    negatives.push([importPath, 'allowlist.out-of-bound-import', state => {
      changedHandle(state.handles, canon, { importPath });
    }]);
  }
  for (const [name, code, mutate] of negatives) {
    await t.test(name, () => {
      const state = { result: structuredClone(result), handles: new Map(allowlist) };
      mutate(state);
      reject(state.result, state.handles, code);
    });
  }

  await t.test('unselected valid handles emit nothing and factories never execute', () => {
    const handles = new Map([...allowlist].map(([id, handle]) => [id, {
      ...handle, factory() { assert.fail('renderer executed a factory'); },
    }]));
    handles.set('x/constructor', {
      ...handles.get(canon),
      declaration: { ...allowlist.get(canon).declaration, implementationId: 'x/constructor' },
      factoryExport: 'createUnused', declarationExport: 'unusedDeclaration', localName: 'unused',
    });
    assert.equal(emitComposition(result, handles), expected);
    changedHandle(handles, 'x/constructor', { localName: 'canonicalizer' });
    reject(result, handles, 'allowlist.duplicate-local-name');
  });
});
