export type Cardinality = "required" | "optional" | "many";
export interface Dependency { slot: string; capability: string; cardinality: Cardinality; min?: number; max?: number; orderBy?: string; }
export interface ModuleDeclaration { id: string; version: string; dependencies: readonly Dependency[]; metadata?: Readonly<Record<string, unknown>>; }
export type JsonValue = null | boolean | number | string | readonly JsonValue[] | { readonly [key: string]: JsonValue };
export const hostileKeys = ["__proto__", "constructor", "then", "café", "ключ"] as const;
export const moduleWithHostileKeys: ModuleDeclaration = { id: "consumer", version: "1.0.0", dependencies: [{ slot: "__proto__", capability: "logging", cardinality: "required" }, { slot: "constructor", capability: "metrics", cardinality: "optional" }, { slot: "then", capability: "storage", cardinality: "many", min: 0, max: 2, orderBy: "id" }], metadata: Object.freeze({ ["__proto__"]: "literal", constructor: "literal", then: "literal", café: "Unicode NFC", ключ: "Unicode Cyrillic" }) };
export function assertJsonValue(value: unknown): asserts value is JsonValue { if (value === null || typeof value === "boolean" || typeof value === "string") return; if (typeof value === "number") { if (Number.isFinite(value)) return; throw new TypeError("unsupported JSON value: non-finite number"); } if (Array.isArray(value)) { if (Object.getPrototypeOf(value) !== Array.prototype || "toJSON" in value) throw new TypeError("unsupported JSON value: array prototype or toJSON"); const ownNames = Object.getOwnPropertyNames(value); const ownSymbols = Object.getOwnPropertySymbols(value); if (ownSymbols.length > 0) throw new TypeError("unsupported JSON value: array symbol property"); for (const key of ownNames) { if (key === "length") continue; if (!/^\d+$/u.test(key) || Number(key) >= value.length) throw new TypeError(`unsupported JSON value at ${key}`); const descriptor = Object.getOwnPropertyDescriptor(value, key); if (!descriptor || !("value" in descriptor) || descriptor.enumerable !== true) throw new TypeError(`unsupported JSON value at ${key}`); assertJsonValue(descriptor.value); } for (let index = 0; index < value.length; index += 1) { if (!Object.hasOwn(value, String(index))) throw new TypeError(`unsupported JSON value: sparse array at ${index}`); } return; } if (typeof value === "object") { const prototype = Object.getPrototypeOf(value); if (prototype !== Object.prototype && prototype !== null) throw new TypeError("unsupported JSON value: object prototype"); if ("toJSON" in value) throw new TypeError("unsupported JSON value: toJSON"); for (const key of Reflect.ownKeys(value)) { if (typeof key !== "string") throw new TypeError("unsupported JSON value: symbol property"); const descriptor = Object.getOwnPropertyDescriptor(value, key); if (!descriptor || !("value" in descriptor) || descriptor.enumerable !== true) throw new TypeError(`unsupported JSON value at ${key}`); assertJsonValue(descriptor.value); } return; } throw new TypeError("unsupported JSON value: primitive"); }
export function canonicalSnapshot(value: unknown): string { assertJsonValue(value); const snapshot = JSON.stringify(value, (_key, nested) => { if (nested && typeof nested === "object" && !Array.isArray(nested)) { const sorted: Record<string, JsonValue> = Object.create(null) as Record<string, JsonValue>; for (const key of Object.keys(nested).sort((a, b) => a < b ? -1 : a > b ? 1 : 0)) sorted[key] = (nested as Record<string, JsonValue>)[key]; return sorted; } return nested; }); if (snapshot === undefined) throw new TypeError("unsupported JSON value: undefined snapshot"); return snapshot; }
export const scenarioNames = ["required", "optional", "many", "missing", "duplicate", "ambiguity", "cycle", "disabled", "unreachable", "multiple roots", "deterministic ordering", "hostile keys", "unknown fields", "no fallback", "serializability", "declaration emit", "no executable import during discovery"] as const;
export const scenarioResults: Readonly<Record<string, string>> = Object.freeze(Object.fromEntries(scenarioNames.map((name) => [name, ["hostile keys", "serializability", "declaration emit"].includes(name) ? "pass" : "fixture-covered"])));
