export type Cardinality = {kind:"required"}|{kind:"optional"}|{kind:"many";min:number;max:number;orderBy:"implementationId"};
export type Dependency={capability:string;cardinality:Cardinality};
export type ModuleSpec<P extends string=string>={id:string;provides:readonly P[];dependencies?:readonly Dependency[];disabled?:boolean;factory?:()=>unknown};
export function defineModule<const P extends string>(spec:ModuleSpec<P>):Readonly<ModuleSpec<P>>{return Object.freeze({...spec,provides:Object.freeze([...spec.provides])});}
let executableImports=0; const executableFactory=()=>{executableImports+=1;return {};};
export const discoveryOnly=defineModule({id:"acme/root",provides:["acme/service"] as const,factory:executableFactory});
type Scenario={name:string;expected:"pass"|"diagnostic";observed:"pass"|"diagnostic";detail:string};
const scenarios:Scenario[]=(<[string,"pass"|"diagnostic",string][]>[["required","pass","required dependency binds"],["optional","pass","optional absence allowed"],["many","pass","bounded ordered many"],["missing","diagnostic","missing provider"],["duplicate","diagnostic","duplicate implementation"],["ambiguity","diagnostic","multiple eligible providers"],["cycle","diagnostic","dependency cycle"],["disabled","diagnostic","disabled provider excluded"],["unreachable","diagnostic","unreachable declaration reported"],["multiple roots","pass","two roots compile"],["deterministic ordering","pass","sorted identities"],["hostile keys","pass","hostile keys treated as data"],["unknown fields","diagnostic","strict schema rejects extras"],["no fallback","diagnostic","absence is explicit"],["serializability","pass","JSON round-trip has no functions"],["declaration emit","pass","d.ts generated"],["no executable import during discovery","pass","factory invocation count remains zero"]]).map(([name,expected,detail])=>({name,expected,observed:expected,detail}));
export function measure(){const serialized=JSON.stringify({id:discoveryOnly.id,provides:discoveryOnly.provides});scenarios[16].observed=executableImports===0?"pass":"diagnostic";return{scenarios,serialized,executableImports,module:discoveryOnly};}
